# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia

notifications:
  email: false

julia:
  - 1.3
  - 1.5
  - nightly

os:
  - linux

dist: bionic

addons:
  apt:
    update: true
    packages:
      - mpich
      - libmpich-dev
      - libhdf5-mpich-dev

env:
  global:
    - JULIA_MPI_BINARY=system
    - JULIA_HDF5_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/mpich

arch:
  - x64

cache:
  directories:
    - ~/.julia/artifacts

script:
  # Force precompilation of packages in serial mode.
  # Also install and build HDF5.jl, and show version info.
  - |
    julia --project -e '
      using Pkg
      using InteractiveUtils
      versioninfo()
      pkg"add HDF5"
      using HDF5
      @show HDF5.libhdf5
      pkg"instantiate"
      pkg"precompile"
      using MPI
      println("\n", MPI.MPI_LIBRARY_VERSION_STRING)'
  - julia --project -e 'import Pkg; Pkg.test(coverage=true)'

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.5
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using PencilArrays
          doctest(PencilArrays)
          include("docs/make.jl")'
      after_success: skip

after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'

# vim: shiftwidth=2
