name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

jobs:
  # Test using system MPI + HDF5.
  # Adapted from https://github.com/JuliaParallel/MPI.jl/blob/0a051294fcc45a329b5f445611791e4bbc6e0f23/.github/workflows/UnitTests.yml#L252
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        version:
          - '1.10'
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: 'pre'
            os: ubuntu-latest
            arch: x64
            experimental: true

    env:
      # JULIA_MPI_TEST_BINARY: system
      OMPI_MCA_btl_base_warn_component_unused: 0
      OMPI_MCA_rmaps_base_oversubscribe: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install MPI via apt
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev libhdf5-openmpi-dev

      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v3
        with:
          cache-registries: "true"

      - name: Add MPIPreferences
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add("MPIPreferences")

      - name: Use system MPI + HDF5
        shell: julia --color=yes --project=. {0}
        run: |
          using MPIPreferences, HDF5
          MPIPreferences.use_system_binary()
          HDF5.API.set_libraries!("/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so", "/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5_hl.so")

      - uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v6
        with:
          files: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install MPI via apt
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev libhdf5-openmpi-dev

      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.12'

      - uses: julia-actions/cache@v3
        with:
          cache-registries: "true"

      - name: Add MPIPreferences
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add("MPIPreferences")

      - name: Use system MPI + HDF5
        shell: julia --color=yes --project=. {0}
        run: |
          using MPIPreferences, HDF5
          MPIPreferences.use_system_binary()
          HDF5.API.set_libraries!("/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so", "/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5_hl.so")

      - name: Install docs dependencies
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()

      - name: Build and deploy
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}

# vim: shiftwidth=2
